api/urls.py
from django.urls import path
from api import views

app_name = 'api'
#ルーティング情報
urlpatterns = [
    path('foods/', views.index, name='index'), #一覧
    path('foods/add/', views.edit, name='add'), #新規
    path('foods/edit/<int:id>/', views.edit, name='edit'), #編集（idを指定）
    path('foods/delete/<int:id>/', views.delete, name='delete'), #削除（idを指定）
]

config/urls.py
from django.urls import path,include

urlpatterns = [
    path('api/', include('api.urls', namespace='api'))
]

api/models.py
from django.db import models


class Food(models.Model):
    name = models.CharField('品物', max_length=50)
    date = models.DateField('消費期限')
    number = models.PositiveIntegerField('数量', blank=True, default=0)

    def __str__(self):
        return self.name

api/forms.py
from django.forms import ModelForm
from api.models import Food
from django import forms

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ('name','date','number')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }

api/views.py
from django.shortcuts import render, get_object_or_404, redirect

from api.models import Food
from api.forms import FoodForm


# 一覧
def index(request):
    # foodモデル全てのレコードを取得してidの昇順に並べる
    foods = Food.objects.all().order_by('id')
    return render(request, 'foods/index.html',{'foods':foods})

# 新規、編集
def edit(request, id=None):
    # GETリクエストの処理
    if id:
        # 編集ボタンを押した場合
        food = get_object_or_404(Food,pk=id)
        # 編集画面フォームを生成
        form = FoodForm(instance=food)
    else:
        # 新規ボタンを押した場合
        food = Food()
        # 新規画面フォームを生成
        form = FoodForm(instance=food)

    # POSTリクエスト（保存）の処理
    if request.method == 'POST':
        # 追記されたフォームデータを渡す
        form = FoodForm(request.POST, instance=food)
        # フォームのバリデーション
        if form.is_valid():
            form.save()
            # 保存後、一覧ページにリダイレクト
            return redirect('api:index')

    # 新規・編集画面を表示
    return render(request, 'foods/edit.html', {'form':form,'id': id})

# 削除
def delete(request, id=None):
    # 指定されたidを元にデータベースから値を取得
    food = get_object_or_404(Food,pk=id)
    # 削除確認画面から送信されたリクエストは削除処理
    if request.method == 'POST':
        food.delete()
        return redirect('api:index')
    #　削除確認画面を表示
    return render(request, 'foods/delete.html', {'food':food,'id': id})

api/templates/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}my foods{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"
        defer></script>
</body>
</html>

api/templates/foods/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
削除確認
{% endblock title %}

{% block content %}
    <h1>削除確認</h1>
    <p>本当に「{{ food.name }}」を削除しますか？</p>
    <form method="post">
        {% csrf_token%}
        <button type="submit" class="btn btn-outline-danger btn-sm me-2">削除する</button>
        <a href="{% url 'api:index' %}" class="btn btn-outline-secondary btn-sm">戻る</a>
    </form>
{% endblock content %}

api/templates/foods/edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
新規作成・編集
{% endblock title %}

{% block content %}
    {% if id %}
    <h1>編集</h1>
    <form action="{% url 'api:edit' id=id %}" method="post">
    {% else %}
    <h1>新規登録</h1>
    <form action="{% url 'api:add' %}" method="post">
    {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group">
            <button type="submit" class="btn btn-outline-primary me-2" >保存</button>
            <a href="{% url 'api:index' %}" class="btn btn-outline-secondary ">戻る</a>
        </div>
    </form>
{% endblock content %}

api/templates/foods/index.html
{% extends "base.html" %}

{% block title %}
期限管理アプリ
{% endblock title %}

{% block content %}
<h1>非常食のデータベース</h1>
<a href="{% url 'api:add' %}" class="btn btn-primary mb-2">新規</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>品物</th>
            <th>消費期限</th>
            <th>数量</th>
            <th>編集と削除</th>
        </tr>
    </thead>
    <tbody>
        {% for food in foods %}
        <tr>
            <td>{{ food.id }}</td>
            <td>{{ food.name }}</td>
            <td>{{ food.date }}</td>
            <td>{{ food.number }}</td>
            <td>
                <a href="{% url 'api:edit' id=food.id %}" class="btn btn-outline-primary btn-sm my-2">編集</a>
                <a href="{% url 'api:delete' id=food.id %}" class="btn btn-outline-danger btn-sm my-2">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}